"""added more columns in users table

Revision ID: 09b9ebe1825f
Revises: f48a1916ef21
Create Date: 2022-12-23 16:12:20.191706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b9ebe1825f'
down_revision = 'f48a1916ef21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dateOfBirth', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profilePicUrl', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phoneVerified', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('emailVerified', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('isVerified', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('isBlocked', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('otpCode', sa.String(), nullable=True))
    op.add_column('users', sa.Column('deviceType', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastLogin', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastLogin')
    op.drop_column('users', 'deviceType')
    op.drop_column('users', 'otpCode')
    op.drop_column('users', 'isBlocked')
    op.drop_column('users', 'isVerified')
    op.drop_column('users', 'emailVerified')
    op.drop_column('users', 'phoneVerified')
    op.drop_column('users', 'profilePicUrl')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    op.drop_column('users', 'dateOfBirth')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
